name: Build mkosi image
on:
  pull_request:
  push:
    branches: [main, ci]

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-24.04

    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@v24.3

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install mtools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools

      - name: build cloud image
        run: |
          mkosi -C images --profile basic
          sha512sum images/Arch-Linux-x86_64-basic.raw
