name: Build reproducible mkosi image
on:
  pull_request:
  push:
    branches: [main, ci]

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    options: --privileged

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          pacman -Syu --noconfirm mkosi mtools grub git

      - name: build reproducible image
        run: |
          mkosi -C reproducible build
          sha512sum reproducible/image.raw

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "reproducible-image.raw"
          path: "reproducible/image.raw"
          overwrite: true
